bollards_api/api/routes.py
from os import environ

from flask_cors import CORS

from bollards_api.models import Bollard
from flask import Blueprint, jsonify, Response

from bollards_api.api.utils import get_neighbours_by_number

api = Blueprint('api', __name__, url_prefix='/api/v1')

CORS(api)

@api.route('/bollards/list')
def bollards_list():
    bollards = Bollard.query.all()
    resp = []
    for bollard in bollards:
        resp.append({
            "id": bollard.id,
            "b_number": bollard.b_number,
            "b_letter": bollard.b_letter,
            "b_name": bollard.b_name,
            "image_icon": bollard.image_icon

        })
    return jsonify(resp)


@api.route('/bollards/list/csv')
def bollards_list_csv():
    """Downloads a csv file with all bollards and their attributes."""
    bollards = Bollard.query.all()
    resp = "id,b_number,b_letter,b_type,b_name,comment,b_lat,b_lng,b_easting,b_northing,b_height,image_icon\n"
    for b in bollards:
        resp += f"{b.id},{b.b_number},{b.b_letter},{b.b_type},{b.b_name},\"{b.comment}\",{b.b_lat},{b.b_lng},{b.b_easting},{b.b_northing},{b.b_height},{environ['FRONTEND_URL']}/static/img/bollards_icon/{b.image_icon}\n"
    return Response(
        resp,
        mimetype="text/csv",
        headers={"Content-disposition":
                 "attachment; filename=bollards_list.csv"})


@api.route('/bollards/markers')
def bollards_markers():
    bollards = Bollard.query.all()
    resp = []
    for bollard in bollards:
        resp.append({
            "id": bollard.id,
            "b_number": bollard.b_number,
            "b_letter": bollard.b_letter,
            "b_name": bollard.b_name,
            "b_type": bollard.b_type,
            "image_icon": bollard.image_icon,
            "b_lat": str(bollard.b_lat),
            "b_lng": str(bollard.b_lng)
        })
    return jsonify(resp)


@api.route('/bollards/details/<int:bollard_id>')
def bollards_details(bollard_id):
    bollard = Bollard.query.filter_by(id=bollard_id).first_or_404()
    images = []
    for img in bollard.images:
        images.append(img.uri)
    neighbours = get_neighbours_by_number(bollard)
        
    return jsonify({
        'id': bollard.id,
        'b_number': bollard.b_number,
        'b_letter': bollard.b_letter,
        'b_type': bollard.b_type,
        'b_name': bollard.b_name,
        'comment': bollard.comment,
        'b_lat': str(bollard.b_lat),
        'b_lng': str(bollard.b_lng),
        'image_icon': bollard.image_icon,
        'images': images,
        'neighbours': neighbours
    })

bollards_api/bollards/routes.py
from datetime import datetime, timezone

from bollards_api import db
from bollards_api.bollards.forms import BollardForm
from bollards_api.bollards.utils import (crop_save_picture_bollard,
                                         get_height_from_coordinates,
                                         get_swiss_coordinates,
                                         save_picture_bollard)
from bollards_api.models import Bimage, Bollard
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

bollards = Blueprint('bollards', __name__)

@bollards.route('/list')
def list_bollards():
    page = request.args.get('page', 1, type=int)
    sort_method = request.args.get('sort', 'latest', type=str)
    if sort_method == 'ndesc':
        bollards = Bollard.query.order_by(Bollard.b_number.desc(), 
                    Bollard.b_letter.desc()).paginate(page=page, per_page=30)
    elif sort_method == 'nasc':
        bollards = Bollard.query.order_by(Bollard.b_number, 
                    Bollard.b_letter).paginate(page=page, per_page=30)
    else:
        bollards = Bollard.query.order_by(Bollard.date_updated.desc()).paginate(page=page, per_page=30)
    return render_template('list.html', title='List', bollards=bollards,
                    sort_method=sort_method)

@bollards.route('/manage/<int:bollard_id>', methods=['GET', 'POST'])
@login_required
def manage(bollard_id):
    form = BollardForm()
    bollard = Bollard.query.filter_by(id=bollard_id).first_or_404()
    if form.validate_on_submit():
        bollard.b_number = form.b_number.data
        bollard.b_letter = form.b_letter.data
        bollard.b_type = form.b_type.data
        bollard.b_name = form.b_name.data
        bollard.comment = form.comment.data
        bollard.b_lat = form.b_lat.data
        bollard.b_lng = form.b_lng.data
        bollard.date_updated = datetime.now(timezone.utc)
        if form.main_image.data:
            picture_file_icon, picture_file = save_picture_bollard(form.main_image.data)
            bollard.image_icon = picture_file_icon
            new_bimage = Bimage(uri=picture_file)
            bollard.images.append(new_bimage)
        
        # fs is a FileStorage type
        if form.images.data[0].filename != '':
            for fs in form.images.data:    
                picture_file = crop_save_picture_bollard(new_picture=fs, folder_path='bollards')
                new_bimage = Bimage(uri=picture_file)
                bollard.images.append(new_bimage)
        current_user.last_lat = form.b_lat.data
        current_user.last_lon = form.b_lng.data
        current_user.last_zoom = form.zoom_level.data
        db.session.commit()
        flash(f'Bollard No {form.b_number.data} has been updated', 'success')
        return redirect(url_for('bollards.list_bollards'))
    
    form.b_number.data = bollard.b_number
    form.b_letter.data = bollard.b_letter
    form.b_type.data = bollard.b_type
    form.b_name.data = bollard.b_name
    form.comment.data = bollard.comment
    form.b_lat.data = bollard.b_lat
    form.b_lng.data = bollard.b_lng
    form.zoom_level.data = current_user.last_zoom
    return render_template('manage.html', title='Manage', bollard=bollard, form=form,
        has_map=True, init_lat=bollard.b_lat, init_lng=bollard.b_lng,
        current_url=request.url)


@bollards.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = BollardForm()
    if form.validate_on_submit():
        if Bollard.query.filter_by(b_number=form.b_number.data, 
                            b_letter=form.b_letter.data.upper()).first():
            flash(f'Bollard No {form.b_number.data} allready exists', 'danger')
        else:
            easting, northing = get_swiss_coordinates(form.b_lat.data, form.b_lng.data)
            height = get_height_from_coordinates(easting, northing)
            new_bollard = Bollard(b_number=form.b_number.data,
                                    b_letter=form.b_letter.data.upper(),
                                    b_type=form.b_type.data, 
                                    b_name=form.b_name.data,
                                    comment=form.comment.data, b_lat=form.b_lat.data,
                                    b_lng=form.b_lng.data, b_easting=easting,
                                    b_northing=northing, b_height=height)
            if form.main_image.data:
                picture_file_icon, picture_file = save_picture_bollard(form.main_image.data)
                new_bollard.image_icon = picture_file_icon
                new_bimage = Bimage(uri=picture_file)
                new_bollard.images.append(new_bimage)
            
            # fs is a FileStorage type
            for fs in form.images.data:
                if fs.filename != '':
                    picture_file = crop_save_picture_bollard(new_picture=fs, folder_path='bollards')
                    new_bimage = Bimage(uri=picture_file)
                    new_bollard.images.append(new_bimage)

            current_user.last_lat = form.b_lat.data
            current_user.last_lon = form.b_lng.data
            current_user.last_zoom = form.zoom_level.data
            db.session.add(new_bollard)
            db.session.commit()
            flash(f'Bollard No {form.b_number.data} Created', 'success')
            return redirect(url_for('bollards.list_bollards'))
    form.zoom_level.data = current_user.last_zoom
    return render_template('manage.html', title='Add', form=form, has_map=True,
                init_lat=current_user.last_lat, init_lng=current_user.last_lon,
                init_zoom=current_user.last_zoom)


@bollards.route('/delete/<int:bollard_id>', methods=['POST'])
@login_required
def delete_bollard(bollard_id):
    bollard = Bollard.query.filter_by(id=bollard_id).first_or_404()
    db.session.delete(bollard)
    db.session.commit()
    flash('Bollard deleted successfully.', 'info')
    return redirect(url_for('bollards.list_bollards'))


@bollards.route('/delete/image/<int:bimage_id>/<int:bollard_id>', methods=['POST'])
@login_required
def delete_image(bimage_id, bollard_id):
    bimage = Bimage.query.filter_by(id=bimage_id).first_or_404()
    db.session.delete(bimage)
    db.session.commit()
    flash('Image deleted successfully.', 'info')
    # Todo: find a way to redirect to image section
    return redirect(url_for('bollards.manage', bollard_id=bollard_id)) 

bollards_api/main/routes.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html')

@main.route('/about')
def about():
    return "42"

bollards_api/users/routes.py
import os
from datetime import datetime, timezone

from bollards_api import bcrypt, db
from bollards_api.models import User
from bollards_api.users.forms import (LoginForm, RegisterForm,
                                      UpdateAccountForm,
                                      UpdateAccountPasswordForm)
from bollards_api.users.utils import save_picture_profile
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

users = Blueprint('users', __name__)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        # print(request.form)
        existing_user = User.query.filter_by(username=form.username.data).first()
        if existing_user and bcrypt.check_password_hash(existing_user.password, form.password.data):
            login_user(existing_user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'Login successful. Welcome {existing_user.username}!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login failed, try again', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if form.validate_on_submit():
        # Secret phrase is needed to 
        if bcrypt.check_password_hash(os.environ['REGISTRATION_SECRET_PHRASE'], form.secret_phrase.data):
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            new_user = User(username=form.username.data, password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            flash(f'Account created. Welcome {form.username.data}. Please log in.', 'success')
            return redirect(url_for('users.login'))
        else:
            flash('Account creation is limited. Please contact the author for specific access', 'warning')
    return render_template('register.html', title='Register', form=form)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account(): 
    form_account = UpdateAccountForm()
    form_password = UpdateAccountPasswordForm()
    form_account_submitted = form_account.submit_account.data
    form_password_submitted = form_password.submit_password.data
    if form_account_submitted:
        accordion_account_open = "show"
        accordion_password_open = ""
    elif form_password_submitted:
        accordion_account_open = ""
        accordion_password_open = "show"
    else:
        accordion_account_open = ""
        accordion_password_open = ""
    # Check which form has been submitted, to make it work, submit buttons must have different names.
    if form_account_submitted and form_account.validate_on_submit():
        if form_account.profile_pic.data:
            picture_file = save_picture_profile(form_account.profile_pic.data)
            # print(picture_file)
            current_user.profile_pic = picture_file
        current_user.username = form_account.username.data
        current_user.date_updated = datetime.now(timezone.utc)
        db.session.commit()
        flash(f'Accound updated, your username is now {form_account.username.data}.', 'success')
    elif form_password_submitted and form_password.validate_on_submit():
        existing_user = User.query.filter_by(username=current_user.username).first()
        if existing_user and bcrypt.check_password_hash(existing_user.password, form_password.old_password.data):
            hashed_password = bcrypt.generate_password_hash(form_password.new_password.data).decode('utf-8')
            current_user.password = hashed_password
            current_user.date_updated = datetime.now(timezone.utc)
            db.session.commit()
            flash(f'Account password updated successfully.', 'success')
        else:
            flash('An error occured when changing the password, please try again.', 'danger')
    form_account.username.data = current_user.username
    profile_pic = url_for('static', filename='img/profile_pics/' + current_user.profile_pic)
    return render_template('account.html', title='Account', 
                            profile_pic=profile_pic,
                            accordion_account_open = accordion_account_open,
                            accordion_password_open = accordion_password_open,
                            form_account=form_account,
                            form_password=form_password)

bollards_api/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

  <!-- Favicon-->
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

  <!--Leaflet Part-->
  {% if has_map %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
      integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
      crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
      integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
      crossorigin=""></script>
  {% endif %}

  {% if title %}
      <title>Bollards API - {{ title }}</title>
  {% else %}
      <title>Bollards API</title>
  {% endif %}
</head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-light bg-steel fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand mr-4" href="/">Bollards API</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('bollards.add') }}">Add</a>
              <a class="nav-item nav-link" href="{{ url_for('bollards.list_bollards') }}">List</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>
      <div>
        {% block content %} {% endblock %}
      </div>
      
    </main>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

bollards_api/templates/home.html
{% extends "base.html" %}
{% block content %}
  <h1 class="text-center">Welcome to Bollards API</h1>
  <div class="p-1 text-center">
    <a href="{{ url_for('users.login') }}"><button class="btn btn-outline-success p-2">Login</button></a>
    <a href="{{ url_for('bollards.add') }}"><button class="btn btn-outline-success p-2">New Bollard</button></a>
    <a href="{{ url_for('bollards.list_bollards') }}"><button class="btn btn-outline-success p-2">List Bollards</button></a>
    <a href="{{ url_for('api.bollards_list_csv') }}"><button class="btn btn-outline-success p-2">Export bollards in csv</button></a>
  </div>
  <div class="card-container p-1">
    <div class="p-1 row text-center justify-content-center">
      <div class="card welcome-card">
        <img src="{{ url_for('static', filename='img/home/website_bollard.jpg') }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class="card-title">Visit bollards.ch</h5>
          <p class="card-text">Discover all bollards between Vaud, Switzerland and France.</p>
          <a href="https://bollards.ch" class="btn btn-success">bollards.ch</a>
        </div>
      </div>
      <div style="width: 30px;"></div>
      <div class="card welcome-card">
        <img src="{{ url_for('static', filename='img/home/github_bollard.jpg') }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h2 class="card-title">Browse the source code on Github</h5>
          <p class="card-text">
            This project is open source, anyone can use or modify the code at his will.
            Check it out!
          </p>
          <a href="https://github.com/JeanmarieAlder/bollards-api" class="btn btn-success m-1">
            <img src="{{ url_for('static', filename='img/home/github_mark.png') }}">
            Bollards-api
          </a>
          <a href="https://github.com/JeanmarieAlder/bollards" class="btn btn-success m-1">
            <img src="{{ url_for('static', filename='img/home/github_mark.png') }}">
            Bollards
          </a>
        </div>
      </div>
    </div>
  </div>
  
  <div class="p-1">
    Welcome to the bollards.ch API.
    This web app is mostly used to retrieve all bollards from the database and for management purposes.
    We currently do not accept new moderators at this point, but feel free to contact the author for more information at wakxy13@gmail.com.
  </div>
  <div class="p-1 text-center">
    <a href="{{ url_for('users.login') }}"><button class="btn btn-outline-success p-2">Login</button></a>
    <a href="{{ url_for('bollards.add') }}"><button class="btn btn-outline-success p-2">New Bollard</button></a>
    <a href="{{ url_for('bollards.list_bollards') }}"><button class="btn btn-outline-success p-2">List Bollards</button></a>
    <a href="{{ url_for('api.bollards_list_csv') }}"><button class="btn btn-outline-success p-2">Export bollards in csv</button></a>
  </div>
  <div class="build-no-div">
    <i>Created by Jean-Marie Alder (<a href="mailto:jeanmarie.alder@gmail.com">jeanmarie.alder@gmail.com</a>) under the MIT license. <b>Build number:</b> %%VERSION%%</i>
  </div>
  
{% endblock content %}

bollards_api/templates/list.html
{% extends "base.html" %}
{% block content %}
  <div class="bollard-list-title-div">
    <span class="bollard-list-title"><h1 class="m-2">Bollards List</h1></span>
    <span style="display: inline-block;">
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle p-2" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          Sort by
        </a>
      
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><a class="dropdown-item" href="{{ url_for('bollards.list_bollards', page=1, sort='nasc') }}">No Ascending</a></li>
          <li><a class="dropdown-item" href="{{ url_for('bollards.list_bollards', page=1, sort='ndesc') }}">No Descending</a></li>
          <li><a class="dropdown-item" href="{{ url_for('bollards.list_bollards', page=1, sort='latest') }}">Recently Updated</a></li>
        </ul>
      </div>
    </span>
    <span style="display: inline-block;">
      <a class="btn btn-success m-2" href="{{ url_for('bollards.add') }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
          <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>
      </a>
    </span>
  </div>
  
  <table class="table">
      <tr>
        <th scope="col">Image</th>
        <th scope="col">No</th>
        <th scope="col">Name</th>
        <th scope="col">Comment</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
      {% for bollard in bollards.items %}
        <tr>
          <td class=""><img class="media-body profile-pic profile-pic-{{bollard.b_type}} p-1" src="{{ url_for('static', filename='img/bollards_icon/' + bollard.image_icon) }}"></td>
          <td style="vertical-align: middle;"><b>No {{bollard.b_number}}{{ bollard.b_letter }}</b></td>
          <td>{{bollard.b_name}}</td>
          <td>{{bollard.comment}}</td>
          <td><a href="{{ url_for('bollards.manage', bollard_id=bollard.id) }}"><button class="btn btn-primary">Edit</button></a></td>
          <td><button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal-{{bollard.id}}">Delete</button></td>
        </tr>

        <!-- Modal -->
        <div class="modal fade" id="deleteModal-{{bollard.id}}" tabindex="-1" aria-labelledby="deleteModal-{{bollard.id}}Label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModal-{{bollard.id}}Label">Delete Bollard</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                Ok, do you really want to delete this bollard?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form action="{{ url_for('bollards.delete_bollard', bollard_id=bollard.id) }}" method="POST">
                  <input id="btn-modal-delete" type="submit" class="btn btn-danger" value="Delete">
                </form>
                
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </table>
    {% for page_num in bollards.iter_pages() %}
      {% if page_num %}
        {% if bollards.page == page_num %}
          <a class="btn btn-success mb-4" href="{{ url_for('bollards.list_bollards', page=page_num, sort=sort_method) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-success mb-4" href="{{ url_for('bollards.list_bollards', page=page_num, sort=sort_method) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}

    
  {% endblock content %}

bollards_api/templates/login.html
{% extends "base.html" %}
{% block content %}
<h1>Login</h1>
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg", autofocus=true) }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}

                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </fieldset>
    </form>
    <div><a href="{{ url_for('users.register') }}">Create an account</a></div>
</div>
{% endblock content %}

bollards_api/templates/register.html
{% extends "base.html" %}
{% block content %}
<h1>Register as a guest</h1>

<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}

                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.secret_phrase.label(class="form-control-label") }}

                {% if form.secret_phrase.errors %}
                    {{ form.secret_phrase(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.secret_phrase.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.secret_phrase(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </fieldset>
        
    </form>
    <p><i>Note: To get editing permissions, contact the author.</i></p>
</div>
{% endblock content %}